/**
 * ------------------------ USER ------------------------
 */
/**
 * User register
 */
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"

/**
 * Get the user
 */
export const GET_THE_USER_LOADING = "GET_THE_USER_LOADING"
export const GET_THE_USER_SUCCESS = "GET_THE_USER_SUCCESS"
export const GET_THE_USER_FAILURE = "GET_THE_USER_FAILURE"

/**
 * Logout clear session
 */
export const LOGOUT_CLEAR_LOADING = "LOGOUT_CLEAR_LOADING"
export const LOGOUT_CLEAR_SUCCESS = "LOGOUT_CLEAR_SUCCESS"
export const LOGOUT_CLEAR_FAILURE = "LOGOUT_CLEAR_FAILURE"

/**
 * Update profile
 */
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

/**
 * Fetch bookmarks
 */
export const FETCH_BOOKMARK_LOADING = "FETCH_BOOKMARK_LOADING"
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS"
export const FETCH_BOOKMARK_FAILURE = "FETCH_BOOKMARK_FAILURE"

/**
 * Fetch bookmark recipes information
 */
export const FETCH_BOOKMARK_INFO_LOADING = "FETCH_BOOKMARK_INFO_LOADING"
export const FETCH_BOOKMARK_INFO_SUCCESS = "FETCH_BOOKMARK_INFO_SUCCESS"
export const FETCH_BOOKMARK_INFO_FAILURE = "FETCH_BOOKMARK_INFO_FAILURE"

/**
 * Delete bookmark recipes
 */
export const DELETE_BOOKMARK_LOADING = "DELETE_BOOKMARK_LOADING"
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS"
export const DELETE_BOOKMARK_FAILURE = "DELETE_BOOKMARK_FAILURE"

/**
 * ------------------------ RECIPE ------------------------
 */
/**
 * Fetch random recipes
 */
export const FETCH_RANDOM_LOADING = "FETCH_RANDOM_LOADING"
export const FETCH_RANDOM_SUCCESS = "FETCH_RANDOM_SUCCESS"
export const FETCH_RANDOM_FAILURE = "FETCH_RANDOM_FAILURE"

/**
 * Fetch recipe information
 */
export const FETCH_RECIPE_INFO_LOADING = "FETCH_RECIPE_INFO_LOADING"
export const FETCH_RECIPE_INFO_SUCCESS = "FETCH_RECIPE_INFO_SUCCESS"
export const FETCH_RECIPE_INFO_FAILURE = "FETCH_RECIPE_INFO_FAILURE"

/**
 * Fetch recipe ingredients and steps
 */
export const FETCH_RECIPE_INGRE_STEPS_LOADING = "FETCH_RECIPE_INGRE_STEPS_LOADING"
export const FETCH_RECIPE_INGRE_STEPS_SUCCESS = "FETCH_RECIPE_INGRE_STEPS_SUCCESS"
export const FETCH_RECIPE_INGRE_STEPS_FAILURE = "FETCH_RECIPE_INGRE_STEPS_FAILURE"

/**
 * Discover search with filters
 */
export const DISCOVER_SEARCH_LOADING = "DISCOVER_SEARCH_LOADING"
export const DISCOVER_SEARCH_SUCCESS = "DISCOVER_SEARCH_SUCCESS"
export const DISCOVER_SEARCH_FAILURE = "DISCOVER_SEARCH_FAILURE"

/**
 * Bookmark recipes
 */
export const BOOKMARK_LOADING = "BOOKMARK_LOADING"
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS"
export const BOOKMARK_FAILURE = "BOOKMARK_FAILURE"

/**
 * Add recipes to planner
 */
export const ADD_RECIPE_PLANNER_LOADING = "ADD_RECIPE_PLANNER_LOADING"
export const ADD_RECIPE_PLANNER_SUCCESS = "ADD_RECIPE_PLANNER_SUCCESS"
export const ADD_RECIPE_PLANNER_FAILURE = "ADD_RECIPE_PLANNER_FAILURE"

/**
 * Add recipes to tracker
 */
export const ADD_RECIPE_TRACKER_LOADING = "ADD_RECIPE_TRACKER_LOADING"
export const ADD_RECIPE_TRACKER_SUCCESS = "ADD_RECIPE_TRACKER_SUCCESS"
export const ADD_RECIPE_TRACKER_FAILURE = "ADD_RECIPE_TRACKER_FAILURE"

/**
 * ------------------------ TRACKER ------------------------
 */

/**
 * ------------------------ GROCERY ------------------------
 */
/**
 * Fetch stores
 */
export const FETCH_STORE_LOADING = "FETCH_STORE_LOADING"
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS"
export const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE"

/**
 * Fetch one store
 */
export const FETCH_ONE_STORE_LOADING = "FETCH_ONE_STORE_LOADING"
export const FETCH_ONE_STORE_SUCCESS = "FETCH_ONE_STORE_SUCCESS"
export const FETCH_ONE_STORE_FAILURE = "FETCH_ONE_STORE_FAILURE"

/**
 * Fetch store items
 */
export const FETCH_STORE_ITEM_LOADING = "FETCH_STORE_ITEM_LOADING"
export const FETCH_STORE_ITEM_SUCCESS = "FETCH_STORE_ITEM_SUCCESS"
export const FETCH_STORE_ITEM_FAILURE = "FETCH_STORE_ITEM_FAILURE"

/**
 * Fetch in cart items
 */
export const FETCH_IN_CART_LOADING = "FETCH_IN_CART_LOADING"
export const FETCH_IN_CART_SUCCESS = "FETCH_IN_CART_SUCCESS"
export const FETCH_IN_CART_FAILURE = "FETCH_IN_CART_FAILURE"

/**
 * Add item to cart
 */
export const ADD_ITEM_CART_LOADING = "ADD_ITEM_CART_LOADING"
export const ADD_ITEM_CART_SUCCESS = "ADD_ITEM_CART_SUCCESS"
export const ADD_ITEM_CART_FAILURE = "ADD_ITEM_CART_FAILURE"

/**
 * Update item to cart
 */
export const UPDATE_ITEM_CART_LOADING = "UPDATE_ITEM_CART_LOADING"
export const UPDATE_ITEM_CART_SUCCESS = "UPDATE_ITEM_CART_SUCCESS"
export const UPDATE_ITEM_CART_FAILURE = "UPDATE_ITEM_CART_FAILURE"

/**
 * Delete item to cart
 */
export const DELETE_ITEM_CART_LOADING = "DELETE_ITEM_CART_LOADING"
export const DELETE_ITEM_CART_SUCCESS = "DELETE_ITEM_CART_SUCCESS"
export const DELETE_ITEM_CART_FAILURE = "DELETE_ITEM_CART_FAILURE"