/**
 * ------------------------ USER ------------------------
 */
/**
 * User register
 */
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"

/**
 * Get the user
 */
export const GET_THE_USER_LOADING = "GET_THE_USER_LOADING"
export const GET_THE_USER_SUCCESS = "GET_THE_USER_SUCCESS"
export const GET_THE_USER_FAILURE = "GET_THE_USER_FAILURE"

/**
 * Logout clear session
 */
export const LOGOUT_CLEAR_LOADING = "LOGOUT_CLEAR_LOADING"
export const LOGOUT_CLEAR_SUCCESS = "LOGOUT_CLEAR_SUCCESS"
export const LOGOUT_CLEAR_FAILURE = "LOGOUT_CLEAR_FAILURE"

/**
 * Update profile
 */
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

/**
 * ------------------------ RECIPE ------------------------
 */
/**
 * Fetch random recipes
 */
export const FETCH_RANDOM_LOADING = "FETCH_RANDOM_LOADING"
export const FETCH_RANDOM_SUCCESS = "FETCH_RANDOM_SUCCESS"
export const FETCH_RANDOM_FAILURE = "FETCH_RANDOM_FAILURE"

/**
 * Fetch recipe information
 */
export const FETCH_RECIPE_INFO_LOADING = "FETCH_RECIPE_INFO_LOADING"
export const FETCH_RECIPE_INFO_SUCCESS = "FETCH_RECIPE_INFO_SUCCESS"
export const FETCH_RECIPE_INFO_FAILURE = "FETCH_RECIPE_INFO_FAILURE"

/**
 * Fetch recipe ingredients and steps
 */
export const FETCH_RECIPE_INGRE_STEPS_LOADING = "FETCH_RECIPE_INGRE_STEPS_LOADING"
export const FETCH_RECIPE_INGRE_STEPS_SUCCESS = "FETCH_RECIPE_INGRE_STEPS_SUCCESS"
export const FETCH_RECIPE_INGRE_STEPS_FAILURE = "FETCH_RECIPE_INGRE_STEPS_FAILURE"

/**
 * Cache recipe ingredients
 */
export const CACHE_RECIPE_INGRE_LOADING = "CACHE_RECIPE_INGRE_LOADING"
export const CACHE_RECIPE_INGRE_SUCCESS = "CACHE_RECIPE_INGRE_SUCCESS"
export const CACHE_RECIPE_INGRE_FAILURE = "CACHE_RECIPE_INGRE_FAILURE"

/**
 * Cache recipe steps
 */
export const CACHE_RECIPE_STEPS_LOADING = "CACHE_RECIPE_STEPS_LOADING"
export const CACHE_RECIPE_STEPS_SUCCESS = "CACHE_RECIPE_STEPS_SUCCESS"
export const CACHE_RECIPE_STEPS_FAILURE = "CACHE_RECIPE_INGRE_FAILURE"
